### PR TITLE
Ignore context args

### LINKED ISSUE #428: Regression bug: unexpected keyword argument 'token_info'
Connexion 1.1.7 breaks my app https://github.com/zalando-incubator/aws-credentials-service (it worked with Connexion 1.1.4 and earlier):

```
[2017-04-05 11:03:07,029] ERROR in app: Exception on /aws-account-roles/jdoe [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/security.py", line 90, in wrapper
    return function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/validation.py", line 299, in wrapper
    return function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/decorator.py", line 42, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/parameter.py", line 188, in wrapper
    return function(**kwargs)
TypeError: get_account_roles() got an unexpected keyword argument 'token_info'
```

There is no parameter `token_info` defined, but Connexion tries to pass it to my handler function now :disappointed:

### PR DESCRIPTION
**Pull request by hjacobs**
Fixes #428.

Allow using handler functions without using `user` or `token_info` args (set by security decorator).

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
👍

**Comment by hjacobs** [comment]
@rafaelcaricio can you release 1.1.8?
