### PR TITLE
Add App(resolver=...) for app-wide default resolver

### LINKED ISSUE #729: Connexion 2.0 release candidate: got an unexpected keyword argument 'resolver'
### Description

I upgraded my Connexion project to use the Connexion 2.0 release candidate, and apparently the new version doesn't implement the `resolver` argument in the `FlaskApp` constructor. 

This code work for Connexion < 2.0, but not for the Connexion 2.0 release candidate:

    connexion_app = connexion.FlaskApp(__name__, specification_dir='swagger/', resolver=RestyResolver('apis'))

### Expected behaviour

No syntax errors. 

### Actual behaviour

    Traceback (most recent call last):
       File "./server/__init__.py", line 12, in create_app
          connexion_app = connexion.FlaskApp(__name__, specification_dir='swagger/', resolver=RestyResolver('apis'))
       File "/usr/local/lib/python3.7/site-packages/connexion/apps/flask_app.py", line 21, in __init__
           super(FlaskApp, self).__init__(import_name, FlaskApi, server=server, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'resolver'

### Steps to reproduce

1. `pip install --pre connexion[swagger-ui]`
2. Run the code in the "description" section

### Additional info:

Output of the commands:

- `python --version`: 3.7.0

### PR DESCRIPTION
**Pull request by dtkav**
Fixes #729 

Changes proposed in this pull request:
 - explicitly allow setting 'resolver' in the App

NB - this worked pre connexion 2.0 because `old_style_options**` passed all kwargs from `App` to `Api`.

### CODE REVIEW

**Comment by dtkav** [comment]
build is broken with new flake8 errors - fix is in #736

File: tests/api/test_bootstrap.py [hunk 1]
```diff
@@ -27,6 +27,17 @@ def test_app_with_relative_path(simple_api_spec_dir, spec):
...
 
+@pytest.mark.parametrize("spec", SPECS)
+def test_app_with_resolver(simple_api_spec_dir, spec):
+    from connexion.resolver import Resolver
+    resolver = Resolver()
+    app = App(__name__, port=5001,
+              specification_dir='..' / simple_api_spec_dir.relative_to(TEST_FOLDER),
+              resolver=resolver)
+    api = app.add_api(spec)
+    assert api.resolver == resolver
```
Comment (jmcs) [inline tests/api/test_bootstrap.py]: Nitpicking, but don't we want to make sure ``api.resolver is resolver``?

Comment (dtkav) [reply tests/api/test_bootstrap.py]: good call

**Comment by dtkav** [comment]
@jmcs any other thoughts on this one?
